default: &default
  adapter: postgresql
  database: default
  pool: 5
  username: andrew
  password: 12345
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: stj_dev

test:
  <<: *default
  database: stj_test

production:
  <<: *default
  database: stj_prod
